
--Edwards dashboard tables truncate script
SELECT 'TRUNCATE TABLE '||UI_SCHEMANAME||'.'||UI_TABLENAME||';','TRUNCATE TABLE '||UI_SCHEMANAME||'.'||UI_SRC_DATA_TABLENAME||';','TRUNCATE TABLE '||UI_SRC_MID_TABLE_NAME||';','TRUNCATE TABLE '||UI_MID_TABLE_NAME||';' FROM ED_EY_TABLES_CONFIG;
--------------------------------------------------------------------------------------------------------------
--Runcontrol tables
SELECT * FROM CLIENT_RUN_CONTROL WHERE CLIENT_ID='1060';--RUN CONTRO NAME (CLIENT_ID, CONTROL_ID, CONTROL_NAME)
SELECT * FROM CLIENT_RUN_CONTROL_STEPS WHERE CLIENT_ID='1060';-- QUERY NAME (STAGE-5,WORK-3,LOAD-4 QUERY ORDER-2) (STEPS ID QUERY ORDER)
SELECT * FROM EXTRACT_TASK;
SELECT * FROM EXTRACT_PROCESS WHERE CLIENT_ID='1060';--EXT FOLDER NAME 
SELECT * FROM TASK_TABLE_LIST;--EXT TABLE NAME
SELECT * FROM USER_QUERY;--ALL ONE CONNECT QUERY
SELECT * FROM CLIENT_TABLE_CATEGORY WHERE CLIENT_ID='1060';-- TABLE NAME SAVE
SELECT * FROM QUERY_TO_TABLE;-- WORK AND STAGE TABLE SAVE 
SELECT * FROM TABLES_IN_USE  WHERE CLIENT_ID='1060';
SELECT * FROM CLIENTS_TABLES;--STAGE TABLE LIST
SELECT * FROM CONV_NAME_TBL;-- CONVERSION NAME TABLE
SELECT * FROM CLIENT_DEST_TBLS;-- (CONVERSION ID ,CLINETID)
SELECT * FROM CLIENT_TABLE_MAP;-- STAGE TABLE NAME CREATE (TRANSFORMATION PROCESS)
SELECT * FROM CLIENT_QUERY_MAP;-- STAGE TABLE NAME MAPPING (TRANSFORMATION PROCESS)
SELECT * FROM CLIENT_COL_MAP;-- COLUMN MAPPING TABLE (TRASFORMATION PROCESS)
SELECT * FROM CLIENT_EXPRESSION;-- EXPRESSION MAPPING (EXPRESSION)
SELECT * FROM CLIENT_XLAT_TBL;-- LKP TABLE NAME 
SELECT * FROM  CLIENT_XLAT_MAP;-- LKP MAPPING
SELECT * FROM CLIENT_RUN_CONTROL_BATCH;-- RUNCONTROL NAME (RUNCONTROL PROCESS)
SELECT * FROM CLIENT_RUNCONTROLEXEC_TBL;-- NEW RUNCONTROL ADDITION TABLE 
SELECT * FROM CLIENT_SCHEDULER;-- NEW SCHEDULER PROCESS
SELECT * FROM OS_EIB_RUNCONTROL_MAP ORDER BY RUNCONTROL_GROUP_ID;--

--------------------------------------------------------------------------------------------------------------------
--Db link scripts

Create database link :-

CREATE DATABASE LINK dblink 
    CONNECT TO remote_user IDENTIFIED BY password
    USING '(DESCRIPTION=
                (ADDRESS=(PROTOCOL=TCP)(HOST=oracledb.example.com)(PORT=1521))
                (CONNECT_DATA=(SERVICE_NAME=service_name))
            )';

CREATE DATABASE LINK MASEKE /*(linkname)*/ CONNECT TO eibp /*(username)*/
IDENTIFIED BY dashb0ard# /*PWD*/ USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=3.231.242.251)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=MSK)))'/*(host)*/;

DROP DATABASE LINK /*(LINK_NAME)*/ ;

-------------------------------------------------------------------------------------------------------------------------
--TO CHECK DATE FORMAT IN ORACLE DATABASE

ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-RR';

SELECT *
FROM NLS_SESSION_PARAMETERS
WHERE PARAMETER = 'NLS_DATE_FORMAT';

-------------------------------------------------------------------------------------------------------------

SELECT IFSCCODE,REGEXP_SUBSTR(IFSCCODE, '^[[:alpha:]]+') AS bank_code FROM BANK; -- To get split words ONLY
	
SELECT IFSCCODE,REGEXP_SUBSTR(IFSCCODE, '\D+') AS branch_code FROM BANK;-- To get split words ONLY
	
SELECT IFSCCODE,REGEXP_SUBSTR(IFSCCODE, '\d+') AS branch_code FROM BANK; -- To get Split numbers only

SELECT XMLCAST(XMLAGG(XMLELEMENT(COLUMN_NAME,COLUMN_NAME ||',') ORDER BY COLUMN_ID) AS CLOB) AS xml_element 
FROM ALL_TAB_COLS WHERE OWNER=USER AND TABLE_NAME='EMPLOYEE_SRC_CHANGES' ORDER BY COLUMN_ID;-- MORE THAN 4000 LENGTH OF LISTAGG 


SELECT IDNO FROM BANK WHERE MOD(IDNO, 2) = 0;-- TO FIND EVEN NUMBERS IN ORACLE
SELECT IDNO FROM BANK WHERE MOD(IDNO, 2) <> 0;-- TO FIND ODD NUMBERS IN ORACLE


-------------------------------------------------------------------------------------------------------------

--Hasc survey extension and insert scripts

/*insert scripts */
--INSERT INTO ENROLLMENT_SURVEYS
SELECT A.ENROLLMENT_ID, 
A.SURVEYTYPE_ID,
CURRENT_DATE EFFDT,
CASE WHEN EFFDT=CURRENT_DATE THEN EFFSEQ+1 ELSE 1 END EFFSEQ,
'A' EFFSTATUS,
A.BEGIN_DT,
--A.END_DT OLD_END_DT,
'2024-05-20' END_DT,
A.ENROLLMENT_STATUS,
A.MODIFIED_BY,
CURRENT_TIMESTAMP MODIFIED_DT
FROM ENROLLMENT_SURVEYS A
WHERE 
A.EFFDT =(SELECT MAX(EFFDT) FROM ENROLLMENT_SURVEYS WHERE ENROLLMENT_ID=A.ENROLLMENT_ID AND SURVEYTYPE_ID=A.SURVEYTYPE_ID ) AND
A.EFFSEQ =(SELECT MAX(EFFSEQ) FROM ENROLLMENT_SURVEYS WHERE ENROLLMENT_ID=A.ENROLLMENT_ID AND SURVEYTYPE_ID=A.SURVEYTYPE_ID AND EFFDT=A.EFFDT) AND
A.EFFSTATUS='A' AND A.ENROLLMENT_ID='600000' AND A.SURVEYTYPE_ID='8';

---------------------------------------------------------------------------------------------------------------------------------------------------------------
--top of the stack

SELECT * FROM ENROLLMENT_SURVEYS A
WHERE 
A.EFFDT =(SELECT MAX(EFFDT) FROM ENROLLMENT_SURVEYS WHERE ENROLLMENT_ID=A.ENROLLMENT_ID AND SURVEYTYPE_ID=A.SURVEYTYPE_ID ) AND
A.EFFSEQ =(SELECT MAX(EFFSEQ) FROM ENROLLMENT_SURVEYS WHERE ENROLLMENT_ID=A.ENROLLMENT_ID AND SURVEYTYPE_ID=A.SURVEYTYPE_ID AND EFFDT=A.EFFDT) AND
A.EFFSTATUS='A' AND A.ENROLLMENT_ID='600000' AND A.SURVEYTYPE_ID='1';

--------------------------------------------------------------------------------------------------------------

--Scheduler insert script

--INSERT INTO CLIENT_SCHEDULER
SELECT '1008'CLIENT_ID, '25'SCHEDULER_ID, '25'TASK_ID, 'FILE_IDENTIFIER'TASK_TYPE,CURRENT_DATE EFFDT,'1' EFFSEQ, 
'A'EFF_STATUS, 'WD to OC-EDW-UK'SCHEDULER_NAME, CURRENT_DATE START_AT, ''END_AT, '0 0/1 * 1/1 * ? *'CRON_CODE, 'Y'IS_ENABLED
FROM CLIENT_SCHEDULER WHERE CLIENT_ID='1000' AND TASK_TYPE='FILE_IDENTIFIER';

--INSERT INTO CLIENT_FILE_IDENTIFY_AND_MOVE
SELECT 
'1008'CLIENT_ID, 'WD to OC-EDW-UK'SCHEDULER_NAME,'D:\sFTP\maseke\Edwards_Implementation\Production\' SOURCE_FOLDER, 
CRITERIA, 'D:\OneConnect\integrationHubFiles\Prod\1008\'TARGET_FOLDER, TASK_TYPE, 
'25'TRIGGER_ID, 'Payroll_Extract*United Kingdom Monthly*.xml''FILEPATTERN,'EDU_UK.xml' OUTPUT_NAME, SUPPORT_FILES, SEQ_ORDER, PGP_ID 
FROM CLIENT_FILE_IDENTIFY_AND_MOVE  WHERE CLIENT_ID='1000';

------------------------------------------------------------------------------------------------------------------

--EDWARDS QUERY COMPARISON
/* TO RUN FOR PRODUCTION ENVIRONMENT*/
SELECT B.CLIENT_ID CLIENT_ID_DEV,C.CLIENT_ID CLIENT_ID_QA,B.QUERY_NAME QUERY_NAME_DEV,C.QUERY_NAME QUERY_NAME_QA,B.QUERY_TEXT QUERY_TEXT_DEV,C.QUERY_TEXT QUERY_TEXT_QA FROM CLIENT_RUN_CONTROL_STEPS A
JOIN (SELECT CLIENT_ID,QUERY_NAME,QUERY_TEXT FROM USER_QUERY A WHERE
                A.EFFDT = (SELECT MAX(EFFDT) FROM USER_QUERY WHERE CLIENT_ID = A.CLIENT_ID AND PROJECT_ID = A.PROJECT_ID AND 
                                QUERY_NAME = A.QUERY_NAME) AND
                A.EFFSEQ = (SELECT MAX(EFFSEQ) FROM USER_QUERY WHERE CLIENT_ID = A.CLIENT_ID AND PROJECT_ID = A.PROJECT_ID AND 
                                QUERY_NAME = A.QUERY_NAME AND EFFDT = A.EFFDT) AND
                A.EFF_STATUS = 'A' AND A.CLIENT_ID = '1000' /*CLIENT ID USE FOR PRODUCTION*/
           ) B ON B.QUERY_NAME = A.OBJ_ID

JOIN (SELECT CLIENT_ID,QUERY_NAME,QUERY_TEXT FROM ONECONNECT.USER_QUERY A WHERE
                A.EFFDT = (SELECT MAX(EFFDT) FROM ONECONNECT.USER_QUERY WHERE CLIENT_ID = A.CLIENT_ID AND PROJECT_ID = A.PROJECT_ID AND 
                                QUERY_NAME = A.QUERY_NAME) AND
                A.EFFSEQ = (SELECT MAX(EFFSEQ) FROM ONECONNECT.USER_QUERY WHERE CLIENT_ID = A.CLIENT_ID AND PROJECT_ID = A.PROJECT_ID AND 
                                QUERY_NAME = A.QUERY_NAME AND EFFDT = A.EFFDT) AND
                A.EFF_STATUS = 'A' AND A.CLIENT_ID = '1000' /*CLIENT ID USE FOR (DEV OR QA)*/ 
           ) C ON C.QUERY_NAME = A.OBJ_ID
WHERE A.CLIENT_ID = '1000' AND A.CONTROL_ID IN ('5','6') AND A.STEPS_ID = '2';

--------------------------------------------------------------------------------------------------------------

SELECT * FROM ALL_TAB_COLUMNS WHERE OWNER=USER AND  TABLE_NAME  IN (SELECT UI_TABLENAME FROM PROJINT6_P.ED_EY_TABLES_CONFIG UNION
SELECT UI_SRC_DATA_TABLENAME FROM PROJINT6_P.ED_EY_TABLES_CONFIG) ORDER BY TABLE_NAME,COLUMN_ID;

SELECT REPLACE(TABLE_NAME,'_HIST',''), COLUMN_NAME FROM ALL_TAB_COLUMNS WHERE OWNER=USER AND  TABLE_NAME  IN (SELECT UI_TABLENAME_HIST FROM PROJINT6_P.ED_EY_TABLES_CONFIG UNION
SELECT UI_SRC_DATA_HIST FROM PROJINT6_P.ED_EY_TABLES_CONFIG) ORDER BY TABLE_NAME,COLUMN_ID;

-------------------------------------------------------------------------------------------------------------

-- To Convert Bytes to Mb for Tablespace in Oracle Synatx.

SELECT SEGMENT_NAME, SEGMENT_TYPE, BYTES AS TOTAL_BYTES, (BYTES / 1024) / 1024 AS SIZE_MB
FROM USER_SEGMENTS 
WHERE SEGMENT_NAME='TABLE NAME' AND --Replace with Table name
SEGMENT_TYPE='TABLE' 

--------------------------------------------------------
2. Query to check the number of times a particular table has been dropped
SELECT ORIGINAL_NAME,COUNT(*) FROM USER_RECYCLEBIN GROUP BY ORIGINAL_NAME HAVING COUNT(*)>1 ORDER BY ORIGINAL_NAME
------------------------------------------------------------------
3. To clear table Space in a Database.
Syntax:-
PURGE RECYCLEBIN 
-----------------------------------------------------------------------
4. To clear a particular table Space in a Database.
Syntax:-
PURGE TABLE TABLE_NAME --Replace with Table name
---------------------------------------------------------------------
1.TO CHANGES THE TABLE FROM MONTHLY TO SEMIMONTHLY FILE 
SELECT * FROM TBL_UMG_RUN_COUNTRY_INFO;
SELECT * FROM TBL_CHG_WHERE_CONFIG;
SELECT * FROM TBL_UMG_SUMMARY_CONFIG;
SELECT * FROM XMLFILE_DATA;

-----------------------------------------------------------------
--Edwards Payresult For Ireland Country
1. To Create Source tables script F FILE CODES 

SELECT A.TABLE_NAME,'SELECT CODE EMPLID,'''||REPLACE(REPLACE(A.TABLE_NAME,'SRC_IRL_F_',''),'_2023_TBL','')||''' CODE,'||B.COLUMN_NAME||' AMOUNT FROM '||A.TABLE_NAME||' WHERE CODE IS NOT NULL UNION ALL' A 
FROM ALL_TABLES A
LEFT JOIN (SELECT TABLE_NAME,COLUMN_NAME
                FROM ALL_TAB_COLUMNS WHERE OWNER=USER AND TABLE_NAME LIKE '%IRL_F_%' AND TABLE_NAME LIKE '%2023%' AND TABLE_NAME NOT IN ('SRC_IRL_F_2023_TBL')
                AND (COLUMN_NAME IN ('AMTBALANCE','BALANCE')))B ON B.TABLE_NAME=A.TABLE_NAME
WHERE A.OWNER=USER AND A.TABLE_NAME LIKE '%IRL_F_%' AND A.TABLE_NAME LIKE '%2023%' AND A.TABLE_NAME NOT IN ('SRC_IRL_F_2023_TBL');

2.To Create Source tables script M FILE CODES

SELECT A.TABLE_NAME,'SELECT CODE EMPLID,'''||REPLACE(REPLACE(A.TABLE_NAME,'SRC_IRL_M_',''),'_2023_TBL','')||''' CODE,'||B.COLUMN_NAME||' AMOUNT FROM '||A.TABLE_NAME||' WHERE CODE IS NOT NULL UNION ALL' A 
FROM ALL_TABLES A
LEFT JOIN (SELECT TABLE_NAME,COLUMN_NAME
                FROM ALL_TAB_COLUMNS WHERE OWNER=USER AND TABLE_NAME LIKE '%IRL_M_%' AND TABLE_NAME LIKE '%2023%' AND TABLE_NAME NOT IN ('SRC_IRL_M_2023_TBL')
                AND (COLUMN_NAME IN ('AMTBALANCE','BALANCE')))B ON B.TABLE_NAME=A.TABLE_NAME
WHERE A.OWNER=USER AND A.TABLE_NAME LIKE '%IRL_M_%' AND A.TABLE_NAME LIKE '%2023%' AND A.TABLE_NAME NOT IN ('SRC_IRL_M_2023_TBL');


SELECT TABLE_NAME,REPLACE(REPLACE(TABLE_NAME,'SRC_IRL_F_',''),'_2023_TBL','')AB FROM ALL_TABLES WHERE OWNER=USER AND TABLE_NAME LIKE '%IRL_F_%' AND TABLE_NAME LIKE '%2023%' AND TABLE_NAME NOT IN ('SRC_IRL_F_2023_TBL');

---------------------------------------------------------------------
--Edwards Payresult For Czech Country
--CZE Source Table creation query generator
WITH QUERY_GENERATOR AS (
SELECT 'select a.emplid,b.code,b.amount from (select column_name emplid from table_name where code = ''EMPLID'') a
join (select code,TO_NUMBER(replace(column_name,'','','''')) amount from table_name where code <> ''EMPLID'' and code is not null) b on 1=1 UNION' QUERY FROM DUAL
)
SELECT replace(REPLACE(QUERY,'column_name','NAME_'||level||''),'table_name','SRC_CZE2_TBL_2023')
FROM QUERY_GENERATOR connect by level <= (select count(*) from all_tab_cols
where owner = user AND TABLE_NAME = 'SRC_CZE2_TBL_2023'
and column_name not in ('TITLE','CODE','TOTAL','MS$LINE_NUM', 'MS$LOAD_DATE', 'MS$CHECKSUM1', 'MS$CHECKSUM2', 'MS$FILENAME'));

-----------
--USA ,PUERTO RICA AMOUNT UPDATE SCRIPT
UPDATE SRC_USA_PAYROLL_ERNS_215_2024
SET CURRENTAMOUNT=CASE WHEN REGEXP_LIKE (CURRENTAMOUNT,'[()]') THEN 
'-'||REGEXP_REPLACE(CURRENTAMOUNT,'[$,()]','') ELSE REGEXP_REPLACE(CURRENTAMOUNT,'[$,()]','')  END
WHERE CURRENTAMOUNT=CURRENTAMOUNT;

-----------------------------------------------------------------------
--EDWARDS PAYRESULTS WORKING TABLES 

SELECT * FROM EXT_PAYROLL_CONFIG;
SELECT * FROM EXT_PAY_E_CODES_EW82024;
SELECT * FROM EXT_PAY_D_CODES_EW82024;
SELECT * FROM LKP_PAYCODE_WDID_EW82024;
SELECT * FROM EXT_PAY_NEG_CODE_CONFIG_2024;
SELECT * FROM EXT_EMPL_NAME_EW8_2024;

------------------------------------------------------------------------
