SELECT DISTINCT
/*Modified by Data Scrience Team*/
CASE WHEN C.PAYRATETYPE = 'Salaried' and C.LOCATIONADDRESSCOUNTRYREGION = 'France'and C.EMPLOYEETYPE IN( 'Apprentice','Student Program / Intern','Trainee') THEN NULL
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '0.0000' AND '11.9500'
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'0')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '11.9501' AND '12.9000' 
          AND (REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1)<>'12')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '12.9001' AND '12.9705' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'12.96')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '12.9706' AND '13.1000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'13')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.1001' AND '13.3000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'13.15')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.3001' AND '13.3500'
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'13.33')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.3501' AND '13.9500' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'13.92') 
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.9501' AND '14.0500' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'14')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '14.0501' AND '14.5000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'14.0625')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '14.5001' AND '40.0000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'39.43')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '40.0001' AND '55.0000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'52')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '55.0001' AND '1600.0000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'1535.90')
          THEN 'Compensation Plan Mismatch'
ELSE
LTRIM(REGEXP_REPLACE(
CASE WHEN C.PAYRATETYPE = 'Hourly' and ROUND(P.TOTALBASEPAYAMOUNT,2)  <> ROUND(REPLACE(PA.AMOUNT,','),2) 
AND ( ROUND(P.TOTALBASEPAYAMOUNT,2)- ROUND(REPLACE(PA.AMOUNT,','),2) )NOT IN('0.01','-0.01')
THEN 'Hourly Rate Mismatch ||' END ||
CASE WHEN C.PAYRATETYPE = 'Hourly' and NVL(SUBSTR( C.TOTALBASEPAYCURRENCY,0,3),'NONE')  <> NVL(SUBSTR(PA.CRCY,0,3),'NONE') THEN 'Hourly Currency Mismatch ||' END ||
CASE WHEN  C.PAYRATETYPE = 'Salaried' and ROUND(CASE WHEN C.CFCCTOTALBASEPAYAMOUNTLOCALCUR='0' THEN PRIMARYCOMPENSATIONBASISAMOUNT ELSE C.CFCCTOTALBASEPAYAMOUNTLOCALCUR END ,2) <> ROUND(REPLACE(PA.ANNUALSALARY,','),2)
AND (ROUND(CASE WHEN C.CFCCTOTALBASEPAYAMOUNTLOCALCUR='0' THEN PRIMARYCOMPENSATIONBASISAMOUNT ELSE C.CFCCTOTALBASEPAYAMOUNTLOCALCUR END ,2)- ROUND(REPLACE(PA.ANNUALSALARY,','),2) )NOT IN('0.01','-0.01')
THEN 'Salaried Rate Mismatch ||' END ||
CASE WHEN  trim(C.PAYRATETYPE) = 'Salaried' and  NVL(SUBSTR(C.TOTALBASEPAYCURRENCY,0,3),'NONE') <> NVL(SUBSTR(PA.CURR,0,3) ,'NONE')THEN 'Salaried Currency Mismatch ||' END ||
CASE WHEN C.PAYRATETYPE = 'Hourly' and PA.WAGETYPE NOT IN ('0010','0035','0080') THEN 'Hourly Incorrect Wage Type ||' END ||
CASE WHEN C.LOCATIONADDRESSCOUNTRYREGION = 'India'  AND C.PAYRATETYPE <> 'Salaried' and ROUND(CASE WHEN C.CFCCTOTALBASEPAYAMOUNTLOCALCUR='0'
THEN PRIMARYCOMPENSATIONBASISAMOUNT ELSE C.CFCCTOTALBASEPAYAMOUNTLOCALCUR END ,2) <> ROUND(REPLACE(PA.ANNUALSALARY,','),2) THEN 'Salaried Rate Mismatch ||'  END ||
CASE WHEN C.LOCATIONADDRESSCOUNTRYREGION  = 'India' and NVL(SUBSTR(C.PRIMARYCOMPENSATIONBASISCURREN,0,3),'NONE') <> NVL(SUBSTR(PA.CURR,0,3),'NONE') THEN 'Salaried Currency Mismatch ||'  END ||
CASE WHEN C.PAYRATETYPE = 'Salaried' and PA.WAGETYPE NOT in ('0010','0020','0030','0080','0082','1500') THEN 'Salaried Incorrect Wage Type ||'  END, '..$')) END ERROR_MESSAGE,/*Modified by Data Scrience Team*/
C.EMPLOYEEID
,C.WORKERHASADDITIONALJOBS
,C.WORKERACTIVE
,C.SAPPERNR
,C.LEGALFIRSTNAME
,C.LEGALLASTNAME
,C.TOTALBASEPAYCURRENCY
, TRIM(TO_CHAR(TO_NUMBER(ROUND(C.CFCCTOTALBASEPAYAMOUNTLOCALCUR,2)), '9999999990.00'))CFCCTOTALBASEPAYAMOUNTLOCALCUR
,C.TOTALBASEPAYANNUALIZEDINREPORT
, TRIM(TO_CHAR(TO_NUMBER(ROUND(C.HOURLYRATEAMOUNT,2)), '9999999990.00') )HOURLYRATEAMOUNT
,C.HOURLYRATECURRENCY
, TRIM(TO_CHAR(TO_NUMBER(ROUND(C.LOCALCURRENCYWAGEWEEKLY,2)), '9999999990.00') )LOCALCURRENCYWAGEWEEKLY
,C.POSITIONID
,C.COMPANY
,C.CF_LRV_PERSONNELAREACODE
,C.LOCATIONADDRESSCOUNTRYREGION
,C.PAYRATETYPE
,C.MANAGEMENTLEVEL
,C.EXEMPT
,C.TIMETYPE
,C.PAYGROUP
,C.EMPLOYEETYPE
,C.CF_LRV_EMPLOYEECONTRACTTYPE
,C.COLLECTIVEAGREEMENT
,C.DCLQUALIFICATIONS
, TRIM(TO_CHAR(TO_NUMBER(ROUND(C.PRIMARYCOMPENSATIONBASISAMOUNT,2)), '9999999990.00'))PRIMARYCOMPENSATIONBASISAMOUNT
,C.PRIMARYCOMPENSATIONBASISCURREN
,PA.PERS
,PA.FIRSTNAME
,PA.LASTNAME
,PA.S
,PA.COCD
,PA.PA
,PA.EEGRP
,PA.ESGRP
,PA.ORG
,PA.POSITION
,PA.BUSA
,PA.TY
,PA.PSA
,PA.PSGROUP
,PA.LV
,PA.CRCY
,PA.WAGETYPE
,PA.TMU
,PA.ENDDATE
,PA.STARTDATE
,PA.NEXTINC
,PA.WKHRS
, TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.ANNUALSALARY,','),2)), '9999999990.00'))ANNUALSALARY
,PA.CURR
, TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00'))AMOUNT
,PA.COL_26
,PA.WORKSCHEDULERULE
,PA.STARTDATEPLANNEDWORKINGTIME
,PA.HOURSPERWEEK
,PA.PERSONNELSUBAREA
,PA.HRSDAY
,P.WORKER PRI_WORKER
,P.EMPLOYEEID PRI_EMPLOYEEID
,P.LOCATIONADDRESSCOUNTRYREGION PRI_LOCATIONADDRESSCOUNTRYREG
,P.ACTIVE PRI_ACTIVE
,P.SUPERVISORYORGANIZATION PRI_SUPERVISORYORGANIZATION
,P.SUPORGREFID PRI_SUPORGREFID
,P.STAFFINGMODEL PRI_STAFFINGMODEL
,P.POSITIONID PRI_POSITIONID
,P.POSITION PRI_POSITION
,P.BUSINESSTITLE PRI_BUSINESSTITLE
,P.JOBTITLE PRI_JOBTITLE
,P.TRANSLATEDBUSINESSTITLE PRI_TRANSLATEDBUSINESSTITLE
,P.JOBPROFILEID PRI_JOBPROFILEID
,P.JOBPROFILE PRI_JOBPROFILE
,P.EMPLOYEETYPE PRI_EMPLOYEETYPE
,P.EMPLOYEETYPEREFID PRI_EMPLOYEETYPEREFID
,P.PAYRATETYPE PRI_PAYRATETYPE
,P.PAYRATETYPEREFID PRI_PAYRATETYPEREFID
,P.TIMETYPE PRI_TIMETYPE
,P.TIMETYPEREFID PRI_TIMETYPEREFID
,P.EXEMPT PRI_EXEMPT
,P.POSITIONWORKFORCECLASSIFICATIO PRI_POSITIONWORKFORCECLASSIFIC
,P.MANAGEMENTLEVEL PRI_MANAGEMENTLEVEL
,P.SCHEDULEDWEEKLYHOURS PRI_SCHEDULEDWEEKLYHOURS
,P.DEFAULTWEEKLYHOURS PRI_DEFAULTWEEKLYHOURS
,P.LOCATION PRI_LOCATION
,P.LOCATIONCOUNTRY PRI_LOCATIONCOUNTRY
,P.LOCATIONSTATEPROVINCE PRI_LOCATIONSTATEPROVINCE
,P.LOCATIONCITY PRI_LOCATIONCITY
,P.LOCATIONREFID PRI_LOCATIONREFID
,P.HOMEADDRESSSTATE PRI_HOMEADDRESSSTATE
,P.PAYGROUP PRI_PAYGROUP
,P.PAYGROUPREFID PRI_PAYGROUPREFID
,P.COMPANY PRI_COMPANY
,P.COMPANYID PRI_COMPANYID
,P.COSTCENTER PRI_COSTCENTER
,P.COSTCENTERID PRI_COSTCENTERID
,P.COSTCENTERREFID PRI_COSTCENTERREFID
,P.COSTCENTERBUSINESSAREA PRI_COSTCENTERBUSINESSAREA
,P.COSTCENTERBAREFID PRI_COSTCENTERBAREFID
,P.COL_41 PRI_COL_41
,P.SEGMENTREFID PRI_SEGMENTREFID
,P.REGION PRI_REGION
,P.REGIONREFID PRI_REGIONREFID
,P.REGIONHIERARCHY PRI_REGIONHIERARCHY
,P.REGIONCODE PRI_REGIONCODE
,P.SAPJOBKEY PRI_SAPJOBKEY
,P.JOBCATEGORY PRI_JOBCATEGORY
,P.LABORAGREEMENTORGANIZATION PRI_LABORAGREEMENTORGANIZATION
,P.LABORAGREEMENTREFID PRI_LABORAGREEMENTREFID
,P.COMPENSATIONGRADE PRI_COMPENSATIONGRADE
,P.COMPGRADEREFID PRI_COMPGRADEREFID
,P.COMPENSATIONGRADEPROFILE PRI_COMPENSATIONGRADEPROFILE
,P.COMPGRADEPROFILEREFID PRI_COMPGRADEPROFILEREFID
,P.CFRPTCOMPGRADEPROFILEPAYSCALEA PRI_CFRPTCOMPGRADEPROFILEPAYSC
,P.CFRPTCOMPGRADEPROFILEPSGROUP PRI_CFRPTCOMPGRADEPROFILEPSGRP
, TRIM(TO_CHAR(TO_NUMBER(ROUND(P.TOTALBASEPAYAMOUNT,2)), '9999999990.00')) PRI_TOTALBASEPAYAMOUNT
,P.TOTALBASEPAYCURRENCY PRI_TOTALBASEPAYCURRENCY
,P.TOTALBASEPAYFREQUENCY PRI_TOTALBASEPAYFREQUENCY
,P.FREQUENCYREFID PRI_FREQUENCYREFID
,P.COMPENSATIONSTEPCURRENT PRI_COMPENSATIONSTEPCURRENT
,P.COMPSTEPREFIDCURRENT PRI_COMPSTEPREFIDCURRENT
,P.EECOMPGRADEJOBPROFILECOMPGRADE PRI_EECOMPGRDJOBPROFCOMPGRD
,P.JOBPROFILECOMPENSATIONGRADE PRI_JOBPROFILECOMPENSATIONGRD
,P.JOBPROFILECOMPGRADEREFID PRI_JOBPROFILECOMPGRADEREFID
,P.JOBPROFILECOMPGRADESTEPLOWESTL PRI_JOBPROFILECOMPGRADESTEPLOW
,P.EESPAYRATEJOBPROFILESLOWESTSTE PRI_EESPAYRATEJOBPROFILESLOWES
,P.CFRPTTFWORKERCOUNTRYHASJOBPROF PRI_CFRPTTFWORKERCOUNTRYHASJOB
,P.COMPPLANS PRI_COMPPLANS
,P.COMPPACKAGEREFID PRI_COMPPACKAGEREFID
,P.COLLECTIVEAGREEMENT PRI_COLLECTIVEAGREEMENT
,P.COLLECTIVEAGREEMENTPROFESSIONA PRI_COLLECTIVEAGREEMENTPROFESS
,P.COLLECTIVEAGREEMENTPOSITION PRI_COLLECTIVEAGREEMENTPOS
,P.COLLECTIVEAGREEMENTCOEFFICIENT PRI_COLLECTIVEAGREEMENTCOEFFIC
,P.REGIONSAPCOCODE PRI_REGIONSAPCOCODE
,P.REGIONSAPPA PRI_REGIONSAPPA
,P.REGIONSAPPSA PRI_REGIONSAPPSA
,P.PACOMPANYCOSTCENTER PRI_PACOMPANYCOSTCENTER
,P.CFRPTTFPOSITIONISINVALIDONZHRM PRI_CFRPTTFPOSITIONISINVALIDON
,P.POSITIONPAEGESGMAPPING PRI_POSITIONPAEGESGMAPPING
,P.VALIDPSASFORPROPOSEDPOSITIONPA PRI_VALIDPSASFORPROPOSEDPOSIPA
,P.EMPLOYEECONTRACT PRI_EMPLOYEECONTRACT
,P.CONTRACTTYPE PRI_CONTRACTTYPE
,P.CONTRACTTYPEREFID PRI_CONTRACTTYPEREFID
,P.CONTRACTSTARTDATE PRI_CONTRACTSTARTDATE
,P.CONTRACTENDDATE PRI_CONTRACTENDDATE
,P.CONTRACTSTATUS PRI_CONTRACTSTATUS
,P.CONTRACTEFFDATE PRI_CONTRACTEFFDATE
,P.CONTRACTPOSITION PRI_CONTRACTPOSITION
,TO_CHAR(P.VISAS) PRI_VISAS
,P.RECENTHIREDATE PRI_RECENTHIREDATE
,P.WORKERHASADDITIONALJOBS PRI_WORKERHASADDITIONALJOBS
,P.SAPPERNR PRI_SAPPERNR
,P.LATESTHIREEVENT PRI_LATESTHIREEVENT
,P.LATESTHIREEVENTEFFECTIVEDATE PRI_LATESTHIREEVENTEFFECTIVEDT
,P.LATESTHIRECOMPLETEDDATETIME PRI_LATESTHIRECOMPLETEDDTTIME
,P.LATESTHIREINITIATEDBY PRI_LATESTHIREINITIATEDBY
,C.MS$LINE_NUM
,C.MS$LOAD_DATE
,C.MS$CHECKSUM1
,C.MS$CHECKSUM2
,C.MS$FILENAME
,C.MS$CHECKSUM1||'|'||C.MS$CHECKSUM2 KEYCOLUMNS,
C.LOCAL_CURRENCY_SALARY_MONTHLY,/*Modified by Data Scrience Team*/
C.FREQUENCY,/*Modified by Data Scrience Team*/
C.SALARY_HOURLY_PLANTYPE,/*Modified by Data Scrience Team*/
C.SALARY_HOURLY_COMPENSATIONPLAN,/*Modified by Data Scrience Team*/
C.SALARY_HOURLY_ASSIGNMENT,/*Modified by Data Scrience Team*/
C.PERIODSALARYPLANTYPE,/*Modified by Data Scrience Team*/
CASE WHEN  C.PAYRATETYPE = 'Salaried' AND (C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN='Service Bonus') THEN CAST('12 Month Plan' AS NVARCHAR2(30)) ELSE C.PERIODSALARYCOMPENSATIONPLAN END PERIODSALARYCOMPENSATIONPLAN,/*Modified by Data Scrience Team*/
C.PERIODSALARYASSIGNMENT,/*Modified by Data Scrience Team*/
C.NATIONALID,/*Modified by Data Scrience Team*/
PA.RESIDUALINDICATOR,/*Modified by Data Scrience Team*/
PA.WORKDAYEMPLOYEEID,/*Modified by Data Scrience Team*/
CASE WHEN C.PAYRATETYPE = 'Salaried' and C.LOCATIONADDRESSCOUNTRYREGION = 'France'and C.EMPLOYEETYPE IN( 'Apprentice','Student Program / Intern','Trainee') THEN NULL 
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' THEN TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000')) 
END CALCULATION,/*Modified by Data Scrience Team*/

CASE WHEN C.PAYRATETYPE = 'Salaried' and C.LOCATIONADDRESSCOUNTRYREGION = 'France'and C.EMPLOYEETYPE IN( 'Apprentice','Student Program / Intern','Trainee') THEN NULL
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '0.0000' AND '11.9500' THEN '0 Month Plan'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '11.9501' AND '12.9000' THEN '12 Month Plan'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '12.9001' AND '12.9705' THEN '12.96 Month Plan'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '12.9706' AND '13.1000' THEN '13 Month Plan'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.1001' AND '13.3000' THEN '13.1538 Month Plan'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.3001' AND '13.3500' THEN '13.33 Month Plan'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.3501' AND '13.9500' THEN '13.92 Month Plan'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.9501' AND '14.0500' THEN '14 Month Plan'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '14.0501' AND '14.5000' THEN '14.0625 Month Plan'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '14.5001' AND '40.0000' THEN '39.43 Month Plan'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '40.0001' AND '55.0000' THEN '52'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '55.0001' AND '1600.0000' THEN '1535.90 Month Plan'
END SAP_COMPENSATION_PLAN /*Modified by Data Scrience Team*/
FROM (SELECT * FROM SRC_DIS_WRKR_CUR_AUDIT_0227
WHERE (SAPPERNR IS NOT NULL AND POSITIONID IS NOT NULL)AND WORKERACTIVE<>'No') C
LEFT JOIN SRC_DIS_PA_0227 PA
 
ON PA.POSITION=C.POSITIONID AND PA.WORKDAYEMPLOYEEID=C.EMPLOYEEID
 
LEFT JOIN SRC_DIS_EMPL_PRI_POSITION_0227 P ON P.POSITIONID=C.POSITIONID
WHERE
PA.PERS is not null and
C.LOCATIONADDRESSCOUNTRYREGION NOT IN ('United States of America','Canada','Bahamas','Puerto Rico','Virgin Islands','Virgin Islands of the US')
AND PA.COCD NOT IN ('1016','1058','3999')
AND LTRIM(REGEXP_REPLACE(
CASE WHEN C.PAYRATETYPE = 'Hourly' and ROUND(P.TOTALBASEPAYAMOUNT,2)  <> ROUND(REPLACE(PA.AMOUNT,','),2)
AND ( ROUND(P.TOTALBASEPAYAMOUNT,2)- ROUND(REPLACE(PA.AMOUNT,','),2) )NOT IN('0.01','-0.01')
THEN 'Hourly Rate Mismatch ||' END ||
CASE WHEN C.PAYRATETYPE = 'Hourly' and NVL(SUBSTR( C.TOTALBASEPAYCURRENCY,0,3),'NONE')  <> NVL(SUBSTR(PA.CRCY,0,3),'NONE') THEN 'Hourly Currency Mismatch ||' END ||
CASE WHEN  C.PAYRATETYPE = 'Salaried' and ROUND(CASE WHEN C.CFCCTOTALBASEPAYAMOUNTLOCALCUR='0' THEN PRIMARYCOMPENSATIONBASISAMOUNT ELSE C.CFCCTOTALBASEPAYAMOUNTLOCALCUR END ,2) <> ROUND(REPLACE(PA.ANNUALSALARY,','),2)
AND (ROUND(CASE WHEN C.CFCCTOTALBASEPAYAMOUNTLOCALCUR='0' THEN PRIMARYCOMPENSATIONBASISAMOUNT ELSE C.CFCCTOTALBASEPAYAMOUNTLOCALCUR END ,2)- ROUND(REPLACE(PA.ANNUALSALARY,','),2) )NOT IN('0.01','-0.01')
THEN 'Salaried Rate Mismatch ||' END ||
CASE WHEN  trim(C.PAYRATETYPE) = 'Salaried' and  NVL(SUBSTR(C.TOTALBASEPAYCURRENCY,0,3),'NONE') <> NVL(SUBSTR(PA.CURR,0,3) ,'NONE')THEN 'Salaried Currency Mismatch ||' END ||
CASE WHEN C.PAYRATETYPE = 'Hourly' and PA.WAGETYPE NOT IN ('0010','0035','0080') THEN 'Hourly Incorrect Wage Type ||' END ||
CASE WHEN C.LOCATIONADDRESSCOUNTRYREGION = 'India'  AND C.PAYRATETYPE <> 'Salaried' and ROUND(CASE WHEN C.CFCCTOTALBASEPAYAMOUNTLOCALCUR='0' THEN PRIMARYCOMPENSATIONBASISAMOUNT ELSE C.CFCCTOTALBASEPAYAMOUNTLOCALCUR END ,2) <> ROUND(REPLACE(PA.ANNUALSALARY,','),2) THEN 'Salaried Rate Mismatch ||'  END ||
CASE WHEN C.LOCATIONADDRESSCOUNTRYREGION  = 'India' and NVL(SUBSTR(C.PRIMARYCOMPENSATIONBASISCURREN,0,3),'NONE') <> NVL(SUBSTR(PA.CURR,0,3),'NONE') THEN 'Salaried Currency Mismatch ||'  END ||
CASE WHEN C.PAYRATETYPE = 'Salaried' and PA.WAGETYPE NOT in ('0010','0020','0030','0080','0082','1500') THEN 'Salaried Incorrect Wage Type ||'  END, '..$'))IS NOT NULL
AND NOT EXISTS (SELECT 1 FROM SRC_DIS_PA_CURR_INTL_TBL FX1 WHERE FX1.MS$CHECKSUM1||'|'|| FX1.MS$CHECKSUM2=C.MS$CHECKSUM1||'|'|| C.MS$CHECKSUM2)
/*Modified by Data Scrience Team*/
AND (CASE WHEN C.PAYRATETYPE = 'Salaried' and C.LOCATIONADDRESSCOUNTRYREGION = 'France'and C.EMPLOYEETYPE IN( 'Apprentice','Student Program / Intern','Trainee') THEN NULL
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '0.0000' AND '11.9500'
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'0')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '11.9501' AND '12.9000' 
          AND (REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1)<>'12')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '12.9001' AND '12.9705' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'12.96')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '12.9706' AND '13.1000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'13')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.1001' AND '13.3000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'13.15')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.3001' AND '13.3500'
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'13.33')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.3501' AND '13.9500' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'13.92') 
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.9501' AND '14.0500' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'14')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '14.0501' AND '14.5000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'14.0625')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '14.5001' AND '40.0000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'39.43')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '40.0001' AND '55.0000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'52')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '55.0001' AND '1600.0000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'1535.90')
          THEN 'Compensation Plan Mismatch'
ELSE
LTRIM(REGEXP_REPLACE(
CASE WHEN C.PAYRATETYPE = 'Hourly' and ROUND(P.TOTALBASEPAYAMOUNT,2)  <> ROUND(REPLACE(PA.AMOUNT,','),2) 
AND ( ROUND(P.TOTALBASEPAYAMOUNT,2)- ROUND(REPLACE(PA.AMOUNT,','),2) )NOT IN('0.01','-0.01')
THEN 'Hourly Rate Mismatch ||' END ||
CASE WHEN C.PAYRATETYPE = 'Hourly' and NVL(SUBSTR( C.TOTALBASEPAYCURRENCY,0,3),'NONE')  <> NVL(SUBSTR(PA.CRCY,0,3),'NONE') THEN 'Hourly Currency Mismatch ||' END ||
CASE WHEN  C.PAYRATETYPE = 'Salaried' and ROUND(CASE WHEN C.CFCCTOTALBASEPAYAMOUNTLOCALCUR='0' THEN PRIMARYCOMPENSATIONBASISAMOUNT ELSE C.CFCCTOTALBASEPAYAMOUNTLOCALCUR END ,2) <> ROUND(REPLACE(PA.ANNUALSALARY,','),2)
AND (ROUND(CASE WHEN C.CFCCTOTALBASEPAYAMOUNTLOCALCUR='0' THEN PRIMARYCOMPENSATIONBASISAMOUNT ELSE C.CFCCTOTALBASEPAYAMOUNTLOCALCUR END ,2)- ROUND(REPLACE(PA.ANNUALSALARY,','),2) )NOT IN('0.01','-0.01')
THEN 'Salaried Rate Mismatch ||' END ||
CASE WHEN  trim(C.PAYRATETYPE) = 'Salaried' and  NVL(SUBSTR(C.TOTALBASEPAYCURRENCY,0,3),'NONE') <> NVL(SUBSTR(PA.CURR,0,3) ,'NONE')THEN 'Salaried Currency Mismatch ||' END ||
CASE WHEN C.PAYRATETYPE = 'Hourly' and PA.WAGETYPE NOT IN ('0010','0035','0080') THEN 'Hourly Incorrect Wage Type ||' END ||
CASE WHEN C.LOCATIONADDRESSCOUNTRYREGION = 'India'  AND C.PAYRATETYPE <> 'Salaried' and ROUND(CASE WHEN C.CFCCTOTALBASEPAYAMOUNTLOCALCUR='0'
THEN PRIMARYCOMPENSATIONBASISAMOUNT ELSE C.CFCCTOTALBASEPAYAMOUNTLOCALCUR END ,2) <> ROUND(REPLACE(PA.ANNUALSALARY,','),2) THEN 'Salaried Rate Mismatch ||'  END ||
CASE WHEN C.LOCATIONADDRESSCOUNTRYREGION  = 'India' and NVL(SUBSTR(C.PRIMARYCOMPENSATIONBASISCURREN,0,3),'NONE') <> NVL(SUBSTR(PA.CURR,0,3),'NONE') THEN 'Salaried Currency Mismatch ||'  END ||
CASE WHEN C.PAYRATETYPE = 'Salaried' and PA.WAGETYPE NOT in ('0010','0020','0030','0080','0082','1500') THEN 'Salaried Incorrect Wage Type ||'  END, '..$')) END) IS NOT NULL;

-----------------------------------------------------------------------------------------------------------------------------------------------------


SELECT DISTINCT
/*Modified by Data Scrience Team*/
CASE WHEN C.PAYRATETYPE = 'Salaried' and C.LOCATIONADDRESSCOUNTRYREGION = 'France'and C.EMPLOYEETYPE IN( 'Apprentice','Student Program / Intern','Trainee') THEN NULL
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '0.0000' AND '11.9500'
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'0')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '11.9501' AND '12.9000' 
          AND (REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1)<>'12')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '12.9001' AND '12.9705' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'12.96')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '12.9706' AND '13.1000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'13')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.1001' AND '13.3000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'13.15')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.3001' AND '13.3500'
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'13.33')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.3501' AND '13.9500' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'13.92') 
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.9501' AND '14.0500' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'14')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '14.0501' AND '14.5000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'14.0625')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '14.5001' AND '40.0000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'39.43')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '40.0001' AND '55.0000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'52')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '55.0001' AND '1600.0000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'1535.90')
          THEN 'Compensation Plan Mismatch'
ELSE
LTRIM(REGEXP_REPLACE(
CASE WHEN C.PAYRATETYPE = 'Hourly' and ROUND(P.TOTALBASEPAYAMOUNT,2)  <> ROUND(REPLACE(PA.AMOUNT,','),2) 
AND ( ROUND(P.TOTALBASEPAYAMOUNT,2)- ROUND(REPLACE(PA.AMOUNT,','),2) )NOT IN('0.01','-0.01')
THEN 'Hourly Rate Mismatch ||' END ||
CASE WHEN C.PAYRATETYPE = 'Hourly' and NVL(SUBSTR( C.TOTALBASEPAYCURRENCY,0,3),'NONE')  <> NVL(SUBSTR(PA.CRCY,0,3),'NONE') THEN 'Hourly Currency Mismatch ||' END ||
CASE WHEN  C.PAYRATETYPE = 'Salaried' and ROUND(CASE WHEN C.CFCCTOTALBASEPAYAMOUNTLOCALCUR='0' THEN PRIMARYCOMPENSATIONBASISAMOUNT ELSE C.CFCCTOTALBASEPAYAMOUNTLOCALCUR END ,2) <> ROUND(REPLACE(PA.ANNUALSALARY,','),2)
AND (ROUND(CASE WHEN C.CFCCTOTALBASEPAYAMOUNTLOCALCUR='0' THEN PRIMARYCOMPENSATIONBASISAMOUNT ELSE C.CFCCTOTALBASEPAYAMOUNTLOCALCUR END ,2)- ROUND(REPLACE(PA.ANNUALSALARY,','),2) )NOT IN('0.01','-0.01')
THEN 'Salaried Rate Mismatch ||' END ||
CASE WHEN  trim(C.PAYRATETYPE) = 'Salaried' and  NVL(SUBSTR(C.TOTALBASEPAYCURRENCY,0,3),'NONE') <> NVL(SUBSTR(PA.CURR,0,3) ,'NONE')THEN 'Salaried Currency Mismatch ||' END ||
CASE WHEN C.PAYRATETYPE = 'Hourly' and PA.WAGETYPE NOT IN ('0010','0035','0080') THEN 'Hourly Incorrect Wage Type ||' END ||
CASE WHEN C.LOCATIONADDRESSCOUNTRYREGION = 'India'  AND C.PAYRATETYPE <> 'Salaried' and ROUND(CASE WHEN C.CFCCTOTALBASEPAYAMOUNTLOCALCUR='0'
THEN PRIMARYCOMPENSATIONBASISAMOUNT ELSE C.CFCCTOTALBASEPAYAMOUNTLOCALCUR END ,2) <> ROUND(REPLACE(PA.ANNUALSALARY,','),2) THEN 'Salaried Rate Mismatch ||'  END ||
CASE WHEN C.LOCATIONADDRESSCOUNTRYREGION  = 'India' and NVL(SUBSTR(C.PRIMARYCOMPENSATIONBASISCURREN,0,3),'NONE') <> NVL(SUBSTR(PA.CURR,0,3),'NONE') THEN 'Salaried Currency Mismatch ||'  END ||
CASE WHEN C.PAYRATETYPE = 'Salaried' and PA.WAGETYPE NOT in ('0010','0020','0030','0080','0082','1500') THEN 'Salaried Incorrect Wage Type ||'  END, '..$')) END ERROR_MESSAGE,/*Modified by Data Scrience Team*/
C.EMPLOYEEID
,C.WORKERHASADDITIONALJOBS
,C.WORKERACTIVE
,C.SAPPERNR
,C.LEGALFIRSTNAME
,C.LEGALLASTNAME
,C.TOTALBASEPAYCURRENCY
, TRIM(TO_CHAR(TO_NUMBER(ROUND(C.CFCCTOTALBASEPAYAMOUNTLOCALCUR,2)), '9999999990.00'))CFCCTOTALBASEPAYAMOUNTLOCALCUR
,C.TOTALBASEPAYANNUALIZEDINREPORT
, TRIM(TO_CHAR(TO_NUMBER(ROUND(C.HOURLYRATEAMOUNT,2)), '9999999990.00') )HOURLYRATEAMOUNT
,C.HOURLYRATECURRENCY
, TRIM(TO_CHAR(TO_NUMBER(ROUND(C.LOCALCURRENCYWAGEWEEKLY,2)), '9999999990.00') )LOCALCURRENCYWAGEWEEKLY
,C.POSITIONID
,C.COMPANY
,C.CF_LRV_PERSONNELAREACODE
,C.LOCATIONADDRESSCOUNTRYREGION
,C.PAYRATETYPE
,C.MANAGEMENTLEVEL
,C.EXEMPT
,C.TIMETYPE
,C.PAYGROUP
,C.EMPLOYEETYPE
,C.CF_LRV_EMPLOYEECONTRACTTYPE
,C.COLLECTIVEAGREEMENT
,C.DCLQUALIFICATIONS
, TRIM(TO_CHAR(TO_NUMBER(ROUND(C.PRIMARYCOMPENSATIONBASISAMOUNT,2)), '9999999990.00'))PRIMARYCOMPENSATIONBASISAMOUNT
,C.PRIMARYCOMPENSATIONBASISCURREN
,PA.PERS
,PA.FIRSTNAME
,PA.LASTNAME
,PA.S
,PA.COCD
,PA.PA
,PA.EEGRP
,PA.ESGRP
,PA.ORG
,PA.POSITION
,PA.BUSA
,PA.TY
,PA.PSA
,PA.PSGROUP
,PA.LV
,PA.CRCY
,PA.WAGETYPE
,PA.TMU
,PA.ENDDATE
,PA.STARTDATE
,PA.NEXTINC
,PA.WKHRS
, TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.ANNUALSALARY,','),2)), '9999999990.00'))ANNUALSALARY
,PA.CURR
, TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00'))AMOUNT
,PA.COL_26
,PA.WORKSCHEDULERULE
,PA.STARTDATEPLANNEDWORKINGTIME
,PA.HOURSPERWEEK
,PA.PERSONNELSUBAREA
,PA.HRSDAY
,P.WORKER PRI_WORKER
,P.EMPLOYEEID PRI_EMPLOYEEID
,P.LOCATIONADDRESSCOUNTRYREGION PRI_LOCATIONADDRESSCOUNTRYREG
,P.ACTIVE PRI_ACTIVE
,P.SUPERVISORYORGANIZATION PRI_SUPERVISORYORGANIZATION
,P.SUPORGREFID PRI_SUPORGREFID
,P.STAFFINGMODEL PRI_STAFFINGMODEL
,P.POSITIONID PRI_POSITIONID
,P.POSITION PRI_POSITION
,P.BUSINESSTITLE PRI_BUSINESSTITLE
,P.JOBTITLE PRI_JOBTITLE
,P.TRANSLATEDBUSINESSTITLE PRI_TRANSLATEDBUSINESSTITLE
,P.JOBPROFILEID PRI_JOBPROFILEID
,P.JOBPROFILE PRI_JOBPROFILE
,P.EMPLOYEETYPE PRI_EMPLOYEETYPE
,P.EMPLOYEETYPEREFID PRI_EMPLOYEETYPEREFID
,P.PAYRATETYPE PRI_PAYRATETYPE
,P.PAYRATETYPEREFID PRI_PAYRATETYPEREFID
,P.TIMETYPE PRI_TIMETYPE
,P.TIMETYPEREFID PRI_TIMETYPEREFID
,P.EXEMPT PRI_EXEMPT
,P.POSITIONWORKFORCECLASSIFICATIO PRI_POSITIONWORKFORCECLASSIFIC
,P.MANAGEMENTLEVEL PRI_MANAGEMENTLEVEL
,P.SCHEDULEDWEEKLYHOURS PRI_SCHEDULEDWEEKLYHOURS
,P.DEFAULTWEEKLYHOURS PRI_DEFAULTWEEKLYHOURS
,P.LOCATION PRI_LOCATION
,P.LOCATIONCOUNTRY PRI_LOCATIONCOUNTRY
,P.LOCATIONSTATEPROVINCE PRI_LOCATIONSTATEPROVINCE
,P.LOCATIONCITY PRI_LOCATIONCITY
,P.LOCATIONREFID PRI_LOCATIONREFID
,P.HOMEADDRESSSTATE PRI_HOMEADDRESSSTATE
,P.PAYGROUP PRI_PAYGROUP
,P.PAYGROUPREFID PRI_PAYGROUPREFID
,P.COMPANY PRI_COMPANY
,P.COMPANYID PRI_COMPANYID
,P.COSTCENTER PRI_COSTCENTER
,P.COSTCENTERID PRI_COSTCENTERID
,P.COSTCENTERREFID PRI_COSTCENTERREFID
,P.COSTCENTERBUSINESSAREA PRI_COSTCENTERBUSINESSAREA
,P.COSTCENTERBAREFID PRI_COSTCENTERBAREFID
,P.COL_41 PRI_COL_41
,P.SEGMENTREFID PRI_SEGMENTREFID
,P.REGION PRI_REGION
,P.REGIONREFID PRI_REGIONREFID
,P.REGIONHIERARCHY PRI_REGIONHIERARCHY
,P.REGIONCODE PRI_REGIONCODE
,P.SAPJOBKEY PRI_SAPJOBKEY
,P.JOBCATEGORY PRI_JOBCATEGORY
,P.LABORAGREEMENTORGANIZATION PRI_LABORAGREEMENTORGANIZATION
,P.LABORAGREEMENTREFID PRI_LABORAGREEMENTREFID
,P.COMPENSATIONGRADE PRI_COMPENSATIONGRADE
,P.COMPGRADEREFID PRI_COMPGRADEREFID
,P.COMPENSATIONGRADEPROFILE PRI_COMPENSATIONGRADEPROFILE
,P.COMPGRADEPROFILEREFID PRI_COMPGRADEPROFILEREFID
,P.CFRPTCOMPGRADEPROFILEPAYSCALEA PRI_CFRPTCOMPGRADEPROFILEPAYSC
,P.CFRPTCOMPGRADEPROFILEPSGROUP PRI_CFRPTCOMPGRADEPROFILEPSGRP
, TRIM(TO_CHAR(TO_NUMBER(ROUND(P.TOTALBASEPAYAMOUNT,2)), '9999999990.00')) PRI_TOTALBASEPAYAMOUNT
,P.TOTALBASEPAYCURRENCY PRI_TOTALBASEPAYCURRENCY
,P.TOTALBASEPAYFREQUENCY PRI_TOTALBASEPAYFREQUENCY
,P.FREQUENCYREFID PRI_FREQUENCYREFID
,P.COMPENSATIONSTEPCURRENT PRI_COMPENSATIONSTEPCURRENT
,P.COMPSTEPREFIDCURRENT PRI_COMPSTEPREFIDCURRENT
,P.EECOMPGRADEJOBPROFILECOMPGRADE PRI_EECOMPGRDJOBPROFCOMPGRD
,P.JOBPROFILECOMPENSATIONGRADE PRI_JOBPROFILECOMPENSATIONGRD
,P.JOBPROFILECOMPGRADEREFID PRI_JOBPROFILECOMPGRADEREFID
,P.JOBPROFILECOMPGRADESTEPLOWESTL PRI_JOBPROFILECOMPGRADESTEPLOW
,P.EESPAYRATEJOBPROFILESLOWESTSTE PRI_EESPAYRATEJOBPROFILESLOWES
,P.CFRPTTFWORKERCOUNTRYHASJOBPROF PRI_CFRPTTFWORKERCOUNTRYHASJOB
,P.COMPPLANS PRI_COMPPLANS
,P.COMPPACKAGEREFID PRI_COMPPACKAGEREFID
,P.COLLECTIVEAGREEMENT PRI_COLLECTIVEAGREEMENT
,P.COLLECTIVEAGREEMENTPROFESSIONA PRI_COLLECTIVEAGREEMENTPROFESS
,P.COLLECTIVEAGREEMENTPOSITION PRI_COLLECTIVEAGREEMENTPOS
,P.COLLECTIVEAGREEMENTCOEFFICIENT PRI_COLLECTIVEAGREEMENTCOEFFIC
,P.REGIONSAPCOCODE PRI_REGIONSAPCOCODE
,P.REGIONSAPPA PRI_REGIONSAPPA
,P.REGIONSAPPSA PRI_REGIONSAPPSA
,P.PACOMPANYCOSTCENTER PRI_PACOMPANYCOSTCENTER
,P.CFRPTTFPOSITIONISINVALIDONZHRM PRI_CFRPTTFPOSITIONISINVALIDON
,P.POSITIONPAEGESGMAPPING PRI_POSITIONPAEGESGMAPPING
,P.VALIDPSASFORPROPOSEDPOSITIONPA PRI_VALIDPSASFORPROPOSEDPOSIPA
,P.EMPLOYEECONTRACT PRI_EMPLOYEECONTRACT
,P.CONTRACTTYPE PRI_CONTRACTTYPE
,P.CONTRACTTYPEREFID PRI_CONTRACTTYPEREFID
,P.CONTRACTSTARTDATE PRI_CONTRACTSTARTDATE
,P.CONTRACTENDDATE PRI_CONTRACTENDDATE
,P.CONTRACTSTATUS PRI_CONTRACTSTATUS
,P.CONTRACTEFFDATE PRI_CONTRACTEFFDATE
,P.CONTRACTPOSITION PRI_CONTRACTPOSITION
,TO_CHAR(P.VISAS) PRI_VISAS
,P.RECENTHIREDATE PRI_RECENTHIREDATE
,P.WORKERHASADDITIONALJOBS PRI_WORKERHASADDITIONALJOBS
,P.SAPPERNR PRI_SAPPERNR
,P.LATESTHIREEVENT PRI_LATESTHIREEVENT
,P.LATESTHIREEVENTEFFECTIVEDATE PRI_LATESTHIREEVENTEFFECTIVEDT
,P.LATESTHIRECOMPLETEDDATETIME PRI_LATESTHIRECOMPLETEDDTTIME
,P.LATESTHIREINITIATEDBY PRI_LATESTHIREINITIATEDBY
,C.MS$LINE_NUM
,C.MS$LOAD_DATE
,C.MS$CHECKSUM1
,C.MS$CHECKSUM2
,C.MS$FILENAME
,C.MS$CHECKSUM1||'|'||C.MS$CHECKSUM2 KEYCOLUMNS,
C.LOCAL_CURRENCY_SALARY_MONTHLY,/*Modified by Data Scrience Team*/
C.FREQUENCY,/*Modified by Data Scrience Team*/
C.SALARY_HOURLY_PLANTYPE,/*Modified by Data Scrience Team*/
C.SALARY_HOURLY_COMPENSATIONPLAN,/*Modified by Data Scrience Team*/
C.SALARY_HOURLY_ASSIGNMENT,/*Modified by Data Scrience Team*/
C.PERIODSALARYPLANTYPE,/*Modified by Data Scrience Team*/
CASE WHEN  C.PAYRATETYPE = 'Salaried' AND (C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN='Service Bonus') THEN CAST('12 Month Plan' AS NVARCHAR2(30)) ELSE C.PERIODSALARYCOMPENSATIONPLAN END PERIODSALARYCOMPENSATIONPLAN,/*Modified by Data Scrience Team*/
C.PERIODSALARYASSIGNMENT,/*Modified by Data Scrience Team*/
C.NATIONALID,/*Modified by Data Scrience Team*/
PA.RESIDUALINDICATOR,/*Modified by Data Scrience Team*/
PA.WORKDAYEMPLOYEEID,/*Modified by Data Scrience Team*/
CASE WHEN C.PAYRATETYPE = 'Salaried' and C.LOCATIONADDRESSCOUNTRYREGION = 'France'and C.EMPLOYEETYPE IN( 'Apprentice','Student Program / Intern','Trainee') THEN NULL 
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' THEN TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000')) 
END CALCULATION,/*Modified by Data Scrience Team*/

CASE WHEN C.PAYRATETYPE = 'Salaried' and C.LOCATIONADDRESSCOUNTRYREGION = 'France'and C.EMPLOYEETYPE IN( 'Apprentice','Student Program / Intern','Trainee') THEN NULL
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '0.0000' AND '11.9500' THEN '0 Month Plan'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '11.9501' AND '12.9000' THEN '12 Month Plan'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '12.9001' AND '12.9705' THEN '12.96 Month Plan'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '12.9706' AND '13.1000' THEN '13 Month Plan'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.1001' AND '13.3000' THEN '13.1538 Month Plan'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.3001' AND '13.3500' THEN '13.33 Month Plan'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.3501' AND '13.9500' THEN '13.92 Month Plan'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.9501' AND '14.0500' THEN '14 Month Plan'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '14.0501' AND '14.5000' THEN '14.0625 Month Plan'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '14.5001' AND '40.0000' THEN '39.43 Month Plan'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '40.0001' AND '55.0000' THEN '52'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '55.0001' AND '1600.0000' THEN '1535.90 Month Plan'
END SAP_COMPENSATION_PLAN /*Modified by Data Scrience Team*/
FROM (SELECT * FROM SRC_DIS_WRKR_CUR_AUDIT_0227
WHERE (SAPPERNR IS NOT NULL AND POSITIONID IS NOT NULL)AND WORKERACTIVE<>'No') C
LEFT JOIN SRC_DIS_PA_0227 PA
 
ON PA.POSITION=C.POSITIONID AND PA.WORKDAYEMPLOYEEID=C.EMPLOYEEID
 
LEFT JOIN SRC_DIS_EMPL_PRI_POSITION_0227 P ON P.POSITIONID=C.POSITIONID
WHERE
PA.PERS is not null and
C.LOCATIONADDRESSCOUNTRYREGION NOT IN ('United States of America','Canada','Bahamas','Puerto Rico','Virgin Islands','Virgin Islands of the US')
AND PA.COCD NOT IN ('1016','1058','3999')
AND 
(LTRIM(REGEXP_REPLACE(
CASE WHEN C.PAYRATETYPE = 'Hourly' and ROUND(P.TOTALBASEPAYAMOUNT,2)  <> ROUND(REPLACE(PA.AMOUNT,','),2)
AND ( ROUND(P.TOTALBASEPAYAMOUNT,2)- ROUND(REPLACE(PA.AMOUNT,','),2) )NOT IN('0.01','-0.01')
THEN 'Hourly Rate Mismatch ||' END ||
CASE WHEN C.PAYRATETYPE = 'Hourly' and NVL(SUBSTR( C.TOTALBASEPAYCURRENCY,0,3),'NONE')  <> NVL(SUBSTR(PA.CRCY,0,3),'NONE') THEN 'Hourly Currency Mismatch ||' END ||
CASE WHEN  C.PAYRATETYPE = 'Salaried' and ROUND(CASE WHEN C.CFCCTOTALBASEPAYAMOUNTLOCALCUR='0' THEN PRIMARYCOMPENSATIONBASISAMOUNT ELSE C.CFCCTOTALBASEPAYAMOUNTLOCALCUR END ,2) <> ROUND(REPLACE(PA.ANNUALSALARY,','),2)
AND (ROUND(CASE WHEN C.CFCCTOTALBASEPAYAMOUNTLOCALCUR='0' THEN PRIMARYCOMPENSATIONBASISAMOUNT ELSE C.CFCCTOTALBASEPAYAMOUNTLOCALCUR END ,2)- ROUND(REPLACE(PA.ANNUALSALARY,','),2) )NOT IN('0.01','-0.01')
THEN 'Salaried Rate Mismatch ||' END ||
CASE WHEN  trim(C.PAYRATETYPE) = 'Salaried' and  NVL(SUBSTR(C.TOTALBASEPAYCURRENCY,0,3),'NONE') <> NVL(SUBSTR(PA.CURR,0,3) ,'NONE')THEN 'Salaried Currency Mismatch ||' END ||
CASE WHEN C.PAYRATETYPE = 'Hourly' and PA.WAGETYPE NOT IN ('0010','0035','0080') THEN 'Hourly Incorrect Wage Type ||' END ||
CASE WHEN C.LOCATIONADDRESSCOUNTRYREGION = 'India'  AND C.PAYRATETYPE <> 'Salaried' and ROUND(CASE WHEN C.CFCCTOTALBASEPAYAMOUNTLOCALCUR='0' THEN PRIMARYCOMPENSATIONBASISAMOUNT ELSE C.CFCCTOTALBASEPAYAMOUNTLOCALCUR END ,2) <> ROUND(REPLACE(PA.ANNUALSALARY,','),2) THEN 'Salaried Rate Mismatch ||'  END ||
CASE WHEN C.LOCATIONADDRESSCOUNTRYREGION  = 'India' and NVL(SUBSTR(C.PRIMARYCOMPENSATIONBASISCURREN,0,3),'NONE') <> NVL(SUBSTR(PA.CURR,0,3),'NONE') THEN 'Salaried Currency Mismatch ||'  END ||
CASE WHEN C.PAYRATETYPE = 'Salaried' and PA.WAGETYPE NOT in ('0010','0020','0030','0080','0082','1500') THEN 'Salaried Incorrect Wage Type ||'  END, '..$'))IS NOT NULL

/*Modified by Data Scrience Team*/
OR (CASE WHEN C.PAYRATETYPE = 'Salaried' and C.LOCATIONADDRESSCOUNTRYREGION = 'France'and C.EMPLOYEETYPE IN( 'Apprentice','Student Program / Intern','Trainee') THEN NULL
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '0.0000' AND '11.9500'
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'0')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '11.9501' AND '12.9000' 
          AND (REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1)<>'12')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '12.9001' AND '12.9705' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'12.96')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '12.9706' AND '13.1000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'13')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.1001' AND '13.3000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'13.15')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.3001' AND '13.3500'
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'13.33')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.3501' AND '13.9500' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'13.92') 
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '13.9501' AND '14.0500' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'14')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '14.0501' AND '14.5000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'14.0625')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '14.5001' AND '40.0000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'39.43')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '40.0001' AND '55.0000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'52')
          THEN 'Compensation Plan Mismatch'
     WHEN C.PAYRATETYPE = 'Salaried' AND TRIM(TO_CHAR(TO_NUMBER(ROUND(REPLACE(PA.AMOUNT,','),2)), '9999999990.00')) <>'0.00' AND 
          TRIM(TO_CHAR(TO_NUMBER(REPLACE(PA.ANNUALSALARY, ',', '')) / TO_NUMBER(REPLACE(PA.AMOUNT, ',', '')) * 1.0,'9999999990.0000'))BETWEEN '55.0001' AND '1600.0000' 
          AND ( C.PERIODSALARYCOMPENSATIONPLAN IS NULL OR C.PERIODSALARYCOMPENSATIONPLAN ='Service Bonus' OR ROUND(REGEXP_SUBSTR(C.PERIODSALARYCOMPENSATIONPLAN,'[^ ]+',1,1),2)<>'1535.90')
          THEN 'Compensation Plan Mismatch' END ) IS NOT NULL)
          AND NOT EXISTS (SELECT 1 FROM SRC_DIS_PA_CURR_INTL_TBL FX1 WHERE FX1.MS$CHECKSUM1||'|'|| FX1.MS$CHECKSUM2=C.MS$CHECKSUM1||'|'|| C.MS$CHECKSUM2) ;


